### ISSUE TITLE
underscore.js is required

### ISSUE THREAD

**Issue by rayphi** [Sebastian-Fitzner/generator-veams#70]
The script (gulp) task fails because of [exoskeleton.js:13](https://github.com/paulmillr/exoskeleton/blob/master/exoskeleton.js#L13) in combination with requirejsOptimize and almond.j.

to get it work again i've only installed undersore `bower install underscore`
and added `underscore: '../bower-components/underscore/underscore'` to main.js

further information down below (error message and setup.json)

```
[12:57:37] Starting 'js:dev'...
[12:57:37] Optimizing C:\dev\demo\resources\js\main.js
[12:57:37]
Tracing dependencies for: ../bower-components/almond/almond
[12:57:38] Error: ENOENT: no such file or directory, open 'C:\dev\demo\resources\js\underscore.js'
In module tree:
    main
      exoskeleton


events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: Error: ENOENT: no such file or directory, open 'C:\dev\demo\resources\js\underscore.js'
In module tree:
    main
      exoskeleton

    at Error (native)

    at C:\dev\demo\node_modules\requirejs\bin\r.js:25150:19
    at C:\dev\demo\node_modules\requirejs\bin\r.js:3056:39
    at C:\dev\demo\node_modules\requirejs\bin\r.js:2996:25
    at Function.prim.nextTick (C:\dev\demo\node_modules\requirejs\bin\r.js:24901:9)
    at Object.p.errback (C:\dev\demo\node_modules\requirejs\bin\r.js:2995:26)
    at Object.p.callback (C:\dev\demo\node_modules\requirejs\bin\r.js:2981:23)
    at Object.p.promise.then (C:\dev\demo\node_modules\requirejs\bin\r.js:3035:23)
    at build (C:\dev\demo\node_modules\requirejs\bin\r.js:25107:12)
    at runBuild (C:\dev\demo\node_modules\requirejs\bin\r.js:27115:17)
    at Object.context.execCb (C:\dev\demo\node_modules\requirejs\bin\r.js:1943:33)
    at Object.Module.check (C:\dev\demo\node_modules\requirejs\bin\r.js:1131:51)
    at Object.<anonymous> (C:\dev\demo\node_modules\requirejs\bin\r.js:1386:34)
    at C:\dev\demo\node_modules\requirejs\bin\r.js:384:23
    at C:\dev\demo\node_modules\requirejs\bin\r.js:1436:21
    at each (C:\dev\demo\node_modules\requirejs\bin\r.js:309:31)
    at Object.Module.emit (C:\dev\demo\node_modules\requirejs\bin\r.js:1435:17)
```

```
{
  "generator-veams": {
    "projectName": "demo",
    "projectAuthor": "raphael",
    "taskRunner": [
      "gulp"
    ],
    "templateEngine": "mangony",
    "mangonyExpress": false,
    "installExtendedLayout": false,
    "installPlugin": false,
    "gulpModules": [
      "gulp-autoprefixer",
      "gulp-bless",
      "gulp-combine-mq",
      "gulp-htmlmin",
      "gulp-iconify",
      "gulp-requirejs-optimize",
      "gulp-uglify"
    ],
    "gruntModules": [],
    "features": [
      "createDevFolder"
    ],
    "jsLibs": [
      "jquery",
      "exoskeleton"
    ],
    "cssLibs": [],
    "testAndQA": false,
    "testAndQALibs": [],
    "veamsPackages": [
      "veamsMethodology",
      "veamsSCSS",
      "veamsJS"
    ],
    "docs": []
  }
}
```

**Comment by Sebastian-Fitzner** [comment]
Thank you for the hint. I will take a look and fix it asap ...

**Comment by Sebastian-Fitzner** [comment]
Issue is solved, thx for the feedback! **Important Notes:** Veams-JS is only usable with Browserify ...
